[package]
name = "tempfile"
description = "Automatically deleted async I/O temporary files."
license = "MIT"
authors = ["Markus Mayer"]
repository = "git@github.com:sunsided/tempfile-rs.git"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21.2", features = ["fs"] }
uuid = { version = "1.2.1", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros"] }
tokio-test = "0.4.2"
