[package]
name = "tempfile"
description = "Automatically deleted async I/O temporary files."
license = "MIT"
authors = ["Markus Mayer"]
repository = "git@github.com:sunsided/tempfile-rs.git"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18.0", features = ["full"] }
uuid = { version = "1.0.0", features = ["v4"] }
