name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Formatting
      run: cargo fmt --check
    - name: Clippy (default features)
      run: cargo clippy
    - name: Clippy (all features)
      run: cargo clippy --all-features
    - name: Build
      run: cargo build --verbose
    - name: Run build tests (default features)
      run: cargo build --tests
    - name: Run build tests (all features)
      run: cargo build --tests --all-features
    - name: Run tests (default features)
      run: cargo test --tests --verbose
    - name: Run tests
      run: cargo test --tests --all-features --verbose
    - name: Run doctests (default features)
      run: cargo test --doc --verbose
    - name: Run doctests (all features)
      run: cargo test --doc --all-features --verbose
